Cluster similar Houses

In [5]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [6]:
url = "https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/house_rental_data.csv.txt"


In [7]:
df = pd.read_csv(url)

In [18]:
df.head()


Unnamed: 0      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  \
0           1  1177.698      2           7        2            2         2   
1           2  2134.800      5           7        4            2         2   
2           3  1138.560      5           7        2            2         1   
3           4  1458.780      2           7        3            2         2   
4           5   967.776     11          14        3            2         2   

   Price  
0  62000  
1  78000  
2  58000  
3  45000  
4  45000

In [15]:
df.set_index("Unnamed: 0")

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
Unnamed: 0                                                                    
1           1177.698      2           7        2            2         2  62000
2           2134.800      5           7        4            2         2  78000
3           1138.560      5           7        2            2         1  58000
4           1458.780      2           7        3            2         2  45000
5            967.776     11          14        3            2         2  45000
...              ...    ...         ...      ...          ...       ...    ...
644         1359.156      7          15        3            2         2  45000
645          377.148      4          10        1            1         1  24800
646          740.064     13          14        1            1         1  45000
647         1707.840      3          14        3            2         2  65000
648         1376.946      6           7        3            2         1  36000

[645 rows x 7 columns]

In [19]:
from sklearn.neighbors import NearestNeighbors


In [20]:
nn= NearestNeighbors(n_neighbors=3)
nn.fit(df)

NearestNeighbors(n_neighbors=3)

In a Jupyter environment, please rerun this cell to show the HTML
representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please 
try loading this page with nbviewer.org

In [21]:
nn.kneighbors(df[:1])

(array([[   0.        , 1071.84905228, 1397.45940781]]),
 array([[  0, 354, 319]], dtype=int64))

In [22]:
df.iloc[[0, 354, 319]]

Unnamed: 0      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  \
0             1  1177.698      2           7        2            2         2   
354         358  1031.820     11          14        3            2         2   
319         323  2099.220      4           8        3            2         2   

     Price  
0    62000  
354  61000  
319  63000

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
minmax = MinMaxScaler()
df.scaled = minmax.fit_transform(df.values)
nn.fit(df.scaled)


NearestNeighbors(n_neighbors=3)

In a Jupyter environment, please rerun this cell to show the HTML
representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please 
try loading this page with nbviewer.org

In [25]:
nn.kneighbors(df.scaled[:1])

(array([[0.        , 0.11068643, 0.12568639]]),
 array([[ 0, 46, 51]], dtype=int64))

In [26]:
df.iloc[[0, 46, 51]]

Unnamed: 0      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  \
0            1  1177.698      2           7        2            2         2   
46          47  1487.244      2           6        2            2         2   
51          52  1494.360      1           5        2            2         2   

    Price  
0   62000  
46  47999  
51  70000