1. Create a null vector of size 10 but the fifth value which is 1.


In [1]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.


In [2]:
import numpy as np
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8


In [5]:
import numpy as np
matrix=np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]


In [6]:
import numpy as np
arr= np.array([1,2,0,0,4,0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


5. Create a 10x10 array with random values and find the minimum and maximum values.


In [7]:
import numpy as np
random_array=np.random.rand(10,10)
minimum_value=random_array.min()
maximum_value=random_array.max()
print(random_array)
print(f"Minimum Value:{minimum_value}")
print(f"Maximum Value:{maximum_value}")

[[0.05552181 0.97723725 0.28256652 0.46604743 0.80177846 0.27319478
  0.68201489 0.35485481 0.58286558 0.36281386]
 [0.31231485 0.50950408 0.93535715 0.45887638 0.92184122 0.71658067
  0.08026903 0.34224225 0.12788665 0.24566758]
 [0.39134769 0.01122829 0.55585931 0.0251603  0.32019744 0.05570728
  0.19736562 0.8946226  0.14981636 0.18221318]
 [0.6981696  0.70696186 0.49030824 0.18620134 0.62518982 0.78772054
  0.24312914 0.97226707 0.32685218 0.24112163]
 [0.05026774 0.72502185 0.89938697 0.76140184 0.8947931  0.83340684
  0.36456778 0.0706109  0.82319019 0.84203833]
 [0.58284721 0.89283164 0.80334995 0.15751913 0.82215786 0.14221743
  0.06498054 0.31436566 0.46286173 0.05637222]
 [0.3970808  0.76772625 0.57704858 0.07879539 0.12260595 0.03002849
  0.80169349 0.68704309 0.42336576 0.38167843]
 [0.32183474 0.38291132 0.27435509 0.78838729 0.67316269 0.05023079
  0.30413684 0.51756883 0.26056191 0.6141287 ]
 [0.62377688 0.48700522 0.61433911 0.265617   0.54303649 0.47169713
  0.53040254

6. Create a random vector of size 30 and find the mean value.


In [10]:
import numpy as np
random_vector = np.random.rand(30)
mean_value=random_vector.mean()
print(random_vector)
print(f"Mean Value:{mean_value}")

[0.50606826 0.0136294  0.90744548 0.46374516 0.16073339 0.8732682
 0.95207424 0.61844484 0.27679231 0.48188478 0.58824555 0.2096633
 0.08853604 0.5142429  0.00722759 0.33854083 0.43801743 0.34873142
 0.05725442 0.83782595 0.14079328 0.73126393 0.20042144 0.69065418
 0.23942562 0.22275121 0.13887027 0.77119539 0.93696611 0.90997925]
Mean Value:0.4554897389747615
